import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Layout",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>This is Dashboard Specific Layout</div>
      {children}
    </>
  );
}
